extends:
  file: ../pipeline.yaml
agent:
  label: jenkins-gradle
  container: 702769831180.dkr.ecr.ap-south-1.amazonaws.com/702769831180/builder-gradle
pipelines:
  pullRequest:
    build:
      steps:
      - sh: gradle clean build
        name: gradle-build
  release:
    setVersion:
      steps:
      - sh: jx step next-version --use-git-tag-only
        name: next-version
        comment: so we can retrieve the version in later steps
      # TODO
      # - sh: mvn versions:set -DnewVersion=\$(cat VERSION)
      - sh: jx step tag --version \$(cat VERSION)
        name: tag-version
    build:
      steps:
      - sh: gradle clean build
        name: gradle-build
