extends:
  file: ../pipeline.yaml
agent:
  label: jenkins-scala
  container: scala
pipelines:
  pullRequest:
    build:
      steps:
      - sh: sbt clean compile assembly
        name: sbt-assembly
  release:
    setVersion:
      steps:
      - sh: jx step next-version --use-git-tag-only
        name: next-version
        comment: so we can retrieve the version in later steps
      # TODO set version with sbt?
      - sh: jx step tag --version \$(cat VERSION)
        name: tag-version
    build:
      steps:
      - sh: sbt clean compile assembly
        name: sbt-assembly
