extends:
  file: ../pipeline.yaml
agent:
  label: jenkins-rust
  container: 702769831180.dkr.ecr.ap-south-1.amazonaws.com/702769831180/builder-rust
pipelines:
  pullRequest:
    build:
      steps:
      - sh: rustup override set nightly
        name: rustup
      - sh: cargo install
        name: cargo-install
      - sh: cp ~/.cargo/bin/REPLACE_ME_APP_NAME .
        name: copy-bin
  release:
    setVersion:
      steps:
      - sh: jx step next-version --use-git-tag-only
        name: next-version
        comment: so we can retrieve the version in later steps
      # TODO set the version in source?
      - sh: jx step tag --version \$(cat VERSION)
        name: tag-version
    build:
      steps:
      - sh: rustup override set nightly
        name: rustup
      - sh: cargo install
        name: cargo-install
      - sh: cp ~/.cargo/bin/REPLACE_ME_APP_NAME .
        name: copy-bin
