extends:
  file: ../pipeline.yaml
agent:
  label: jenkins-go
  container: 702769831180.dkr.ecr.ap-south-1.amazonaws.com/702769831180/builder-go
pipelines:
  release:
    setVersion:
      steps:
      - sh: jx step next-version --use-git-tag-only --tag
        name: tag-version
