agent:
  label: jenkins-go
  container: 702769831180.dkr.ecr.ap-south-1.amazonaws.com/702769831180/builder-go
pipelines:
  pullRequest:
    build:
      steps:
      - sh: jx step custom pipeline
        name: build
  release:
    build:
      steps:
      - sh: jx step custom pipeline
        name: build
