agent:
  label: jenkins-go
  container: go
pipelines:
  pullRequest:
    build:
      steps:
      - sh: jx step custom pipeline
        name: build
  release:
    build:
      steps:
      - sh: jx step custom pipeline
        name: build
