extends:
  file: ../pipeline.yaml
agent:
  label: jenkins-maven
  container: 702769831180.dkr.ecr.ap-south-1.amazonaws.com/702769831180/builder-maven
pipelines:
  pullRequest:
    build:
      steps:
      - sh: mvn versions:set -DnewVersion=$PREVIEW_VERSION
        name: set-version
      - sh: mvn install
        name: mvn-install
  release:
    setVersion:
      steps:
      - sh: jx step next-version --filename pom.xml
        name: next-version
        comment: so we can retrieve the version in later steps
      - sh: jx step tag --version \$(cat VERSION)
        name: tag-version
    build:
      steps:
      - sh: mvn clean deploy
        name: mvn-deploy
